name: angularDartRemote
version: 0.0.1
author: ne4istb
description: Search in angular docs by server query
dependencies:
  angular: "1.1.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
  http_server: ">=0.9.5+1 <0.10.0"
  redstone: ">=0.5.18 <0.6.0"
  shelf_static: ">=0.2.2 <0.3.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    html_files:
      - lib/search_result/search_result.html
      - lib/spinner/spinner.html
- $dart2js:
    minify: true
